<?php

/**
 * @file
 * new_mobile_changes.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function new_mobile_changes_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-BaVbtp0nDAhYeQn9dDsOWECWAoR2r9yd'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BaVbtp0nDAhYeQn9dDsOWECWAoR2r9yd',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-V5VY4NoBmsg3vfANfnUCtpUuyRX3Y9zp'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'V5VY4NoBmsg3vfANfnUCtpUuyRX3Y9zp',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Mobile Frameworks',
    'visibility' => 0,
  );

  $export['facetapi-nEqVwHLaEFhdAuTf8OWC3rvlGBHjvHeS'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nEqVwHLaEFhdAuTf8OWC3rvlGBHjvHeS',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
