<?php
/**
 * Created by PhpStorm.
 * User: kapilbulchandani
 * Date: 5/18/17
 * Time: 7:53 PM
 */

function trend_analysis_theme($existing, $type, $theme, $path) {
    return array(
        'trend_analysis_graph_page' => array(
            'template' => 'trend-analysis-graph-page',
            'variables' => array('nid' => NULL),
            'path' => drupal_get_path('module', 'trend_analysis') . '/templates',
        ),
      'trend_analysis_sparkline_page' => array(
        'template' => 'trend-analysis-sparkline-page',
        'variables' => array('nid' => NULL),
        'path' => drupal_get_path('module', 'trend_analysis') . '/templates',
      ),
      'trend_analysis_multivalgraph_page' => array(
        'template' => 'trend-analysis-multivalgraph-page',
        'variables' => array('nid' => NULL),
        'path' => drupal_get_path('module', 'trend_analysis') . '/templates',
      ),
      'trend_analysis_multivalspark_page' => array(
        'template' => 'trend-analysis-multivalspark-page',
        'variables' => array('nid' => NULL),
        'path' => drupal_get_path('module', 'trend_analysis') . '/templates',
      ),
        'trend_analysis_datatable_page' => array(
            'template' => 'trend-analysis-datatable-page',
            'variables' => array('nid' => NULL),
            'path' => drupal_get_path('module', 'trend_analysis') . '/templates',
        )
    );
}

function trend_analysis_block_info() {
    $blocks['trends_dnssec'] = array(
        // info: The name of the block.
        'info' => t('DNSSEC Trend Analysis Chart'),
        'cache' => DRUPAL_NO_CACHE
    );
  $blocks['trends_dnssec_sparkline'] = array(
    // info: The name of the block.
    'info' => t('DNSSEC Trend Analysis Sparkline'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['trends_dap'] = array(
    'info' => t('DAP Trend Analysis Chart'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['trends_dap_sparkline'] = array(
    'info' => t('DAP Trend Analysis Sparkline'),
    'cache' => DRUPAL_NO_CACHE
  );
    $blocks['trends_ipv6'] = array(
        'info' => t('IPv6 Trend Analysis Chart'),
        'cache' => DRUPAL_NO_CACHE
    );
  $blocks['trends_ipv6_sparkline'] = array(
    'info' => t('IPv6 Trend Analysis Sparkline'),
    'cache' => DRUPAL_NO_CACHE
  );
    $blocks['trends_m1513'] = array(
        'info' => t('M-15-13 and BOD 18-01 Trend Analysis Chart'),
        'cache' => DRUPAL_NO_CACHE
    );
  $blocks['trends_m1513_sparkline'] = array(
    'info' => t('M-15-13 and BOD 18-01 Trend Analysis Sparkline'),
    'cache' => DRUPAL_NO_CACHE
  );
    $blocks['trends_freerc4'] = array(
        'info' => t('Free of RC4/3DES and SSLv2/SSLv3 Trend Analysis Chart'),
        'cache' => DRUPAL_NO_CACHE
    );
  $blocks['trends_freerc4_sparkline'] = array(
    'info' => t('Free of RC4/3DES and SSLv2/SSLv3 Trend Analysis Sparkline'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['trends_accessible_chart'] = array(
    'info' => t('Accessibility Trend Analysis Chart'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['trends_accessible_chart'] = array(
    'info' => t('Accessibility Trend Analysis Chart'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['trends_ssl'] = array(
    'info' => t('SSL Trend Analysis Chart'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['trends_https'] = array(
    'info' => t('HTTPS Trend Analysis Chart'),
    'cache' => DRUPAL_NO_CACHE
  );
  $blocks['trends_mobile_spark'] = array(
    'info' => t('Mobile Sparkline Trend Analysis Chart'),
    'cache' => DRUPAL_NO_CACHE
  );
    $blocks['trends_mobile_chart'] = array(
        'info' => t('Mobile Trend Analysis Chart'),
        'cache' => DRUPAL_NO_CACHE
    );
    $blocks['trends_data_table'] = array(
        'info' => t('Trend Analysis Table'),
        'cache' => DRUPAL_NO_CACHE
    );


    return $blocks;
}


function trend_analysis_block_view($delta = 0) {
    // The $delta parameter tells us which block is being requested.
    $block = array();
    $trend_node = node_load(arg(1));
    $trend_vars['trend_title'] = $trend_node->title;
    switch ($delta) {
        case 'trends_dnssec':
            $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_dnssec_score_value as score_val from node_revision a , field_revision_field_dnssec_score b where b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc;", array(':nid' => arg(1)));
            $trend_arr = array();
            foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_arr[$result->scandate] = (int)$result->score_val;
            }
            $trend_vars['trend_arr'] = $trend_arr;
            $dates = array_keys($trend_vars['trend_arr']);
            $compliance = array_values($trend_vars['trend_arr']);
            $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
            $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
            $trend_vars['compliance'] = $compliance;
            $trend_vars['noncompliance'] = $noncompliance;
            $trend_vars['dates'] = $dates;
            $trend_vars['container'] = 'container1';
          $trend_vars['blockname'] = 'trends_dnssec';

            $analysis_output =  theme('trend_analysis_graph_page', array('trend_vars' => $trend_vars));
            $block = array(
                'subject' => t('DNSSEC Trend Analysis Chart - '.$trend_vars['trend_title']),
                'content' => $analysis_output,
            );
            break;

        case 'trends_dap':

            $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_dap_score_value as score_val from node_revision a , field_revision_field_dap_score b where b.revision_id=a.vid and a.nid=:nid  order by a.timestamp asc", array(':nid' => arg(1)));
            $trend_arr = array();
            foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_arr[$result->scandate] = (int)$result->score_val;
            }
            $trend_vars['trend_arr'] = $trend_arr;
            $dates = array_keys($trend_vars['trend_arr']);
            $compliance = array_values($trend_vars['trend_arr']);
            $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
            $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
            $trend_vars['compliance'] = $compliance;
            $trend_vars['noncompliance'] = $noncompliance;
            $trend_vars['dates'] = $dates;
            $trend_vars['container'] = 'container2';
          $trend_vars['blockname'] = 'trends_dap';
            $analysis_output =  theme('trend_analysis_graph_page', array('trend_vars' => $trend_vars));
            $block = array(
                'subject' => t('DAP Trend Analysis Chart - '.$trend_vars['trend_title']),
                'content' => $analysis_output,
            );
            break;
        case 'trends_ipv6':

            $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_ipv6_score_value as score_val from node_revision a , field_revision_field_ipv6_score b where  b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc;", array(':nid' => arg(1)));
            $trend_arr = array();
            foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_arr[$result->scandate] = (int)$result->score_val;
            }
            $trend_vars['trend_arr'] = $trend_arr;
            $dates = array_keys($trend_vars['trend_arr']);
            $compliance = array_values($trend_vars['trend_arr']);
            $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
            $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
            $trend_vars['compliance'] = $compliance;
            $trend_vars['noncompliance'] = $noncompliance;
            $trend_vars['dates'] = $dates;
            $trend_vars['container'] = 'container3';
          $trend_vars['blockname'] = 'trends_ipv6';
          $analysis_output =  theme('trend_analysis_graph_page', array('trend_vars' => $trend_vars));
            $block = array(
                'subject' => t('IPV6 Trend Analysis Chart - '.$trend_vars['trend_title']),
                'content' => $analysis_output,
            );
            break;
        case 'trends_m1513':

            $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_m15_13_compliance_score_value as score_val from node_revision a , field_revision_field_m15_13_compliance_score b where  b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc", array(':nid' => arg(1)));
            $trend_arr = array();
            foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_arr[$result->scandate] = (int)$result->score_val;
            }
            $trend_vars['trend_arr'] = $trend_arr;
            $dates = array_keys($trend_vars['trend_arr']);
            $compliance = array_values($trend_vars['trend_arr']);
            $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
            $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
            $trend_vars['compliance'] = $compliance;
            $trend_vars['noncompliance'] = $noncompliance;
            $trend_vars['dates'] = $dates;
            $trend_vars['container'] = 'container4';
          $trend_vars['blockname'] = 'trends_m1513';
          $analysis_output =  theme('trend_analysis_graph_page', array('trend_vars' => $trend_vars));
            $block = array(
                'subject' => t('M-15-13 Trend Analysis Chart - '.$trend_vars['trend_title']),
                'content' => $analysis_output,
            );
            break;
        case 'trends_freerc4':

            $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_free_of_insecr_prot_score_value as score_val from node_revision a , field_revision_field_free_of_insecr_prot_score b where  b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc", array(':nid' => arg(1)));
            $trend_arr = array();
            foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_arr[$result->scandate] = (int)$result->score_val;
            }
            $trend_vars['trend_arr'] = $trend_arr;
            $dates = array_keys($trend_vars['trend_arr']);
            $compliance = array_values($trend_vars['trend_arr']);
            $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
            $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
            $trend_vars['compliance'] = $compliance;
            $trend_vars['noncompliance'] = $noncompliance;
            $trend_vars['dates'] = $dates;
            $trend_vars['container'] = 'container5';
          $trend_vars['blockname'] = 'trends_freerc4';
          $analysis_output =  theme('trend_analysis_graph_page', array('trend_vars' => $trend_vars));
            $block = array(
                'subject' => t('Free of RC4/3DES and SSLv2/SSLv3 Trend Analysis Chart - '.$trend_vars['trend_title']),
                'content' => $analysis_output,
            );
            break;
      case 'trends_dnssec_sparkline':
        $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_dnssec_score_value as score_val from node_revision a , field_revision_field_dnssec_score b where b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc;", array(':nid' => arg(1)));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
            if($result->score_val == '100')
                $trend_arr[$result->scandate] = '1';
            elseif($result->score_val == '0')
                $trend_arr[$result->scandate] = '-1';
            elseif($result->score_val == NULL || $result->score_val == '')
                $trend_arr[$result->scandate] = '0';
        }
        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -1));
        $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 1), 0));
        $trend_vars['compliance'] = $compliance;
        $trend_vars['noncompliance'] = $noncompliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['container'] = 'container10';
        $trend_vars['blockname'] = 'trends_dnssec_sparkline';

        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
      case 'trends_dap_sparkline':

        $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_dap_score_value as score_val from node_revision a , field_revision_field_dap_score b where b.revision_id=a.vid and a.nid=:nid  order by a.timestamp asc", array(':nid' => arg(1)));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          if($result->score_val == '100')
            $trend_arr[$result->scandate] = '1';
          elseif($result->score_val == '0')
            $trend_arr[$result->scandate] = '-1';
          elseif($result->score_val == NULL || $result->score_val == '')
              $trend_arr[$result->scandate] = '0';
        }
        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -1));
        $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 1), 0));
        $trend_vars['compliance'] = $compliance;
        $trend_vars['noncompliance'] = $noncompliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['container'] = 'container11';
        $trend_vars['blockname'] = 'trends_dap_sparkline';
        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));

          $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
      case 'trends_ipv6_sparkline':

        $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_ipv6_score_value as score_val from node_revision a , field_revision_field_ipv6_score b where  b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc;", array(':nid' => arg(1)));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
            if($result->score_val == '100')
                $trend_arr[$result->scandate] = '1';
            elseif($result->score_val == '0')
                $trend_arr[$result->scandate] = '-1';
            elseif($result->score_val == NULL || $result->score_val == '')
                $trend_arr[$result->scandate] = '0';
        }
        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
        $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
        $trend_vars['compliance'] = $compliance;
        $trend_vars['noncompliance'] = $noncompliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['container'] = 'container12';
        $trend_vars['blockname'] = 'trends_ipv6_sparkline';
        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
      case 'trends_m1513_sparkline':

        $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_m15_13_compliance_score_value as score_val from node_revision a , field_revision_field_m15_13_compliance_score b where  b.revision_id=a.vid  and a.nid=:nid order by a.timestamp asc", array(':nid' => arg(1)));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
            if($result->score_val == '100')
                $trend_arr[$result->scandate] = '1';
            elseif($result->score_val == '0')
                $trend_arr[$result->scandate] = '-1';
            elseif($result->score_val == NULL || $result->score_val == '')
                $trend_arr[$result->scandate] = '0';
        }
        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
        $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
        $trend_vars['compliance'] = $compliance;
        $trend_vars['noncompliance'] = $noncompliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['container'] = 'container13';
        $trend_vars['blockname'] = 'trends_m1513_sparkline';
        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
      case 'trends_freerc4_sparkline':

        $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_free_of_insecr_prot_score_value as score_val from node_revision a , field_revision_field_free_of_insecr_prot_score b where  b.revision_id=a.vid  and a.nid=:nid order by a.timestamp asc", array(':nid' => arg(1)));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
            if($result->score_val == '100')
                $trend_arr[$result->scandate] = '1';
            elseif($result->score_val == '0')
                $trend_arr[$result->scandate] = '-1';
            elseif($result->score_val == NULL || $result->score_val == '')
                $trend_arr[$result->scandate] = '0';
        }
        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        $noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
        $noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
        $trend_vars['compliance'] = $compliance;
        $trend_vars['noncompliance'] = $noncompliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['container'] = 'container14';
        $trend_vars['blockname'] = 'trends_freerc4_sparkline';
        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
      case 'trends_accessible_chart':
        $allscanids = dotgov_common_siteAsocScanids(arg(1));
        $query = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') as scandate, a.vid from node_revision a, node b  where  a.nid=b.nid and b.type='508_scan_information' and a.nid=:nid  group by scandate order by a.timestamp asc", array(':nid' => $allscanids['508_scan_information']));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_arr[$result->scandate] = (int)$result->vid;
        }
        $query1 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_accessible_group_colorcont_value as score_val from node_revision a , field_revision_field_accessible_group_colorcont b where  b.revision_id=a.vid  and a.nid=:nid  group by scandate order by a.timestamp asc", array(':nid' => $allscanids['508_scan_information']));
        $trend_color = array();
        foreach ($query1 as $result1) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_color[$result1->scandate] = (int)$result1->score_val;
        }

        $query2 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_accessible_group_htmlattri_value as score_val from node_revision a , field_revision_field_accessible_group_htmlattri b where  b.revision_id=a.vid  and a.nid=:nid   group by scandate order by a.timestamp asc", array(':nid' => $allscanids['508_scan_information']));
        $trend_htmlattrib = array();
        foreach ($query2 as $result2) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_htmlattrib[$result2->scandate] = (int)$result2->score_val;
        }

        $query3 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_accessible_group_missingim_value as score_val from node_revision a , field_revision_field_accessible_group_missingim b where  b.revision_id=a.vid  and a.nid=:nid  group by scandate order by a.timestamp asc", array(':nid' => $allscanids['508_scan_information']));
        $trend_missing = array();
        foreach ($query3 as $result3) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_missing[$result3->scandate] = (int)$result3->score_val;
        }

        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        $trend_vars['col_contrast'] = $trend_color;
        $trend_vars['html_attrib'] = $trend_htmlattrib;
        $trend_vars['miss_image'] = $trend_missing;
        $trend_vars['compliance'] = $compliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['container'] = 'container15';
        $trend_vars['blockname'] = 'trends_accessible_chart';
        $analysis_output =  theme('trend_analysis_multivalgraph_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => 'Accessibility Trend Analysis Chart - '.$trend_vars['trend_title'],
          'content' => $analysis_output,
        );
        break;
      case 'trends_ssl':

        $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_ssl_score_value as score_val from node_revision a , field_revision_field_ssl_score b where  b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc", array(':nid' => arg(1)));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_arr[$result->scandate] = (int)$result->score_val;
        }
        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        //$noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
        //$noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
        $trend_vars['compliance'] = $compliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['blockname'] = 'trends_ssl';
        $trend_vars['container'] = 'container16';
        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
      case 'trends_https':

        $query = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_https_score_value as score_val from node_revision a , field_revision_field_https_score b where  b.revision_id=a.vid  and a.nid=:nid  order by a.timestamp asc", array(':nid' => arg(1)));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_arr[$result->scandate] = (int)$result->score_val;
        }
        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_vars['trend_arr']);
        $compliance = array_values($trend_vars['trend_arr']);
        //$noncompliance = array_replace($compliance, array_fill_keys(array_keys($compliance, 0), -100));
        //$noncompliance = array_replace($noncompliance, array_fill_keys(array_keys($noncompliance, 100), 0));
        $trend_vars['compliance'] = $compliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['blockname'] = 'trends_https';
        $trend_vars['container'] = 'container17';
        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
        case 'trends_mobile_chart':
            $allscanids = dotgov_common_siteAsocScanids(arg(1));
            //dsm($allscanids);
            $query = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') as scandate, a.vid from node_revision a, node b  where  a.nid=b.nid and b.type='mobile_scan_information' and a.nid=:nid   group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
            $trend_arr = array();
            foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_arr[$result->scandate] = (int)$result->vid;
            }
            $query1 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_mobile_overall_score_value as score_val from node_revision a , field_revision_field_mobile_overall_score b where  b.revision_id=a.vid  and a.nid=:nid  group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
            $trend_moboverall = array();
            foreach ($query1 as $result1) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_moboverall[$result1->scandate] = (int)$result1->score_val;
            }

            $query2 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_mobile_performance_score_value as score_val from node_revision a , field_revision_field_mobile_performance_score b where  b.revision_id=a.vid  and a.nid=:nid   group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
            $trend_mobperfrm = array();
            foreach ($query2 as $result2) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_mobperfrm[$result2->scandate] = (int)$result2->score_val;
            }

            $query3 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_mobile_usability_score_value as score_val from node_revision a , field_revision_field_mobile_usability_score b where  b.revision_id=a.vid  and a.nid=:nid   group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
            $trend_mobusab = array();
            foreach ($query3 as $result3) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
                $trend_mobusab[$result3->scandate] = (int)$result3->score_val;
            }

            $trend_vars['trend_arr'] = $trend_arr;
            $dates = array_keys($trend_moboverall);
            $compliance = array_values($trend_moboverall);
            $trend_vars['moboverall'] = $trend_moboverall;
            $trend_vars['mobperfrm'] = $trend_mobperfrm;
            $trend_vars['mobusab'] = $trend_mobusab;
            $trend_vars['compliance'] = $compliance;
            $trend_vars['dates'] = $dates;
            $trend_vars['container'] = 'container19';
            $trend_vars['scanreportid'] = $allscanids['mobile_scan_information'];
            $trend_vars['blockname'] = 'trends_mobile_chart';
            //$analysis_output =  theme('trend_analysis_multivalspark_page', array('trend_vars' => $trend_vars));
            $analysis_output =  theme('trend_analysis_multivalgraph_page', array('trend_vars' => $trend_vars));
            $block = array(
                'subject' => 'Mobile Trend Analysis Chart - '.$trend_vars['trend_title'],
                'content' => $analysis_output,
            );
            break;
      case 'trends_mobile_spark':
        $allscanids = dotgov_common_siteAsocScanids(arg(1));
        //dsm($allscanids);
        $query = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') as scandate, a.vid from node_revision a, node b  where  a.nid=b.nid and b.type='mobile_scan_information' and a.nid=:nid   group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
        $trend_arr = array();
        foreach ($query as $result) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_arr[$result->scandate] = (int)$result->vid;
        }
        $query1 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,max(field_mobile_overall_score_value) as score_val from node_revision a , field_revision_field_mobile_overall_score b where  b.revision_id=a.vid  and a.nid=:nid  group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
        //dsm($allscanids['mobile_scan_information']);
        $trend_moboverall = array();
        foreach ($query1 as $result1) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          //$trend_moboverall[$result1->scandate] = (int)$result1->score_val;

            if($result1->score_val == NULL || $result1->score_val == '')
                $trend_moboverall[$result1->scandate] = '-1';
            else
                $trend_moboverall[$result1->scandate] = (int)$result1->score_val;

        }

        $query2 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_mobile_performance_score_value as score_val from node_revision a , field_revision_field_mobile_performance_score b where  b.revision_id=a.vid  and a.nid=:nid  group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
        $trend_mobperfrm = array();
        foreach ($query2 as $result2) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_mobperfrm[$result2->scandate] = (int)$result2->score_val;
        }

        $query3 = db_query("select FROM_UNIXTIME(timestamp,'%Y/%m/%d') as scandate,field_mobile_usability_score_value as score_val from node_revision a , field_revision_field_mobile_usability_score b where  b.revision_id=a.vid  and a.nid=:nid  group by scandate order by a.timestamp asc", array(':nid' => $allscanids['mobile_scan_information']));
        $trend_mobusab = array();
        foreach ($query3 as $result3) {
//                $daptime = format_date($result->scandate ,'custom','m-d-Y h A');
          $trend_mobusab[$result3->scandate] = (int)$result3->score_val;
        }

        $trend_vars['trend_arr'] = $trend_arr;
        $dates = array_keys($trend_moboverall);
        $compliance = array_values($trend_moboverall);
        $trend_vars['moboverall'] = $trend_moboverall;
        $trend_vars['mobperfrm'] = $trend_mobperfrm;
        $trend_vars['mobusab'] = $trend_mobusab;
        $trend_vars['compliance'] = $compliance;
        $trend_vars['dates'] = $dates;
        $trend_vars['container'] = 'container18';
        $trend_vars['scanreportid'] = $allscanids['mobile_scan_information'];
        $trend_vars['blockname'] = 'trends_mobile_spark';
        //$analysis_output =  theme('trend_analysis_multivalspark_page', array('trend_vars' => $trend_vars));
        $analysis_output =  theme('trend_analysis_sparkline_page', array('trend_vars' => $trend_vars));
        $block = array(
          'subject' => NULL,
          'content' => $analysis_output,
        );
        break;
        case 'trends_data_table':
            $query1 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_dap_score_value score_val  from node_revision a, field_revision_field_dap_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr1 = array();
            foreach ($query1 as $result1) {
                $trend_arr1[$result1->scandate]['dap'] = $result1->score_val;
            }
            $query2 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_dnssec_score_value score_val  from node_revision a, field_revision_field_dnssec_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr2 = array();
            foreach ($query2 as $result2) {
                $trend_arr2[$result2->scandate]['dnssec'] = $result2->score_val;
            }
            $query3 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_free_of_insecr_prot_score_value score_val  from node_revision a, field_revision_field_free_of_insecr_prot_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr3 = array();
            foreach ($query3 as $result3) {
                $trend_arr3[$result3->scandate]['insec'] = $result3->score_val;
            }
            $query4 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_https_score_value score_val  from node_revision a, field_revision_field_https_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr4 = array();
            foreach ($query4 as $result4) {
                $trend_arr4[$result4->scandate]['https'] = $result4->score_val;
            }

            $query5 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_ipv6_score_value score_val  from node_revision a, field_revision_field_ipv6_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr5 = array();
            foreach ($query5 as $result5) {
                $trend_arr5[$result5->scandate]['ipv6'] = $result5->score_val;
            }

            $query6 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_m15_13_compliance_score_value score_val  from node_revision a, field_revision_field_m15_13_compliance_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr6 = array();
            foreach ($query6 as $result6) {
                $trend_arr6[$result6->scandate]['m15'] = $result6->score_val;
            }

            $query7 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_mobile_overall_score_value score_val  from node_revision a, field_revision_field_mobile_overall_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr7 = array();
            foreach ($query7 as $result7) {
                $trend_arr7[$result7->scandate]['mobovr'] = $result7->score_val;
            }

            $query8 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_mobile_performance_score_value score_val  from node_revision a, field_revision_field_mobile_performance_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr8 = array();
            foreach ($query8 as $result8) {
                $trend_arr8[$result8->scandate]['mobperf'] = $result8->score_val;
            }

            $query9 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_mobile_usability_score_value score_val  from node_revision a, field_revision_field_mobile_usability_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr9 = array();
            foreach ($query9 as $result9) {
                $trend_arr9[$result9->scandate]['mobusab'] = $result9->score_val;
            }

            $query10 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_site_speed_score_value score_val  from node_revision a, field_revision_field_site_speed_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr10 = array();
            foreach ($query10 as $result10) {
                $trend_arr10[$result10->scandate]['sitespeed'] = $result10->score_val;
            }

            $query11 = db_query("select FROM_UNIXTIME(a.timestamp,'%Y/%m/%d') scandate,field_ssl_score_value score_val  from node_revision a, field_revision_field_ssl_score b where a.nid=b.entity_id and a.vid=b.revision_id and a.nid=:nid group by scandate order by a.timestamp desc", array(':nid' => arg(1)));
            $trend_arr11 = array();
            foreach ($query11 as $result11) {
                $trend_arr11[$result11->scandate]['ssl'] = $result11->score_val;
            }

            $trend_arr = array_merge_recursive($trend_arr1,$trend_arr2,$trend_arr3,$trend_arr4,$trend_arr5,$trend_arr6,$trend_arr7,$trend_arr8,$trend_arr9,$trend_arr10,$trend_arr11);


            $trend_vars['trend_arr'] = $trend_arr;

            $trend_vars['container'] = 'container1';
            $trend_vars['blockname'] = 'trends_data_table';

            $analysis_output =  theme('trend_analysis_datatable_page', array('trend_vars' => $trend_vars));
            $block = array(
                'subject' => t('View All Historical Scan Score Data for '.$trend_vars['trend_title']),
                'content' => $analysis_output,
            );
            break;
    }

    return $block;
}

function recursive_array_replace ($find, $replace, $array) {
    if (!is_array($array)) {
        return str_replace($find, $replace, $array);
    }

    $newArray = [];
    foreach ($array as $key => $value) {
        $newArray[$key] = recursive_array_replace($find, $replace, $value);
    }
    return $newArray;
}

