<?php

/**
 * @file
 * apachesolrsearch.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function apachesolrsearch_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['apachesolr_search-mlt-001'] = array(
    'cache' => 4,
    'custom' => 0,
    'delta' => 'mlt-001',
    'module' => 'apachesolr_search',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['apachesolr_search-sort'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sort',
    'module' => 'apachesolr_search',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-0BB0WVi1QTSWY5phPp0f1B1gbChnr10h'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0BB0WVi1QTSWY5phPp0f1B1gbChnr10h',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Font Script Applications',
    'visibility' => 0,
  );

  $export['facetapi-0OQoXNYK0MNrGXqwK1NxKHgFGWEHsSu9'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0OQoXNYK0MNrGXqwK1NxKHgFGWEHsSu9',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-0bmcBZHG3l0rA5HI4pazplC5igekGvpf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0bmcBZHG3l0rA5HI4pazplC5igekGvpf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-0ll6V3NOJOkCwbeS7ERkuk5vAy6zkGhK'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0ll6V3NOJOkCwbeS7ERkuk5vAy6zkGhK',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-0mmkJY0hSs1XLAsMpuNJcZqlcqpW01p1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0mmkJY0hSs1XLAsMpuNJcZqlcqpW01p1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-10kynqNNEoRbBm51u60fScx9j14gqULd'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '10kynqNNEoRbBm51u60fScx9j14gqULd',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1ABvAl9NxANNxxtFhM7hTtnD0jUbKj1p'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1ABvAl9NxANNxxtFhM7hTtnD0jUbKj1p',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1Brjup2039un8vJge03Aojlf2mrhpMf2'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1Brjup2039un8vJge03Aojlf2mrhpMf2',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1DMFCEtrNh3vA7DxeyOmMYTqsOgdqlTi'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1DMFCEtrNh3vA7DxeyOmMYTqsOgdqlTi',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Session Secure Renegotiation',
    'visibility' => 0,
  );

  $export['facetapi-1FpmY1XKlLKGgbDsWjf4t7pQk10QPg0z'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1FpmY1XKlLKGgbDsWjf4t7pQk10QPg0z',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Web Server',
    'visibility' => 0,
  );

  $export['facetapi-1HuV60oTwnapD5yUfRMhRxt9ukJUZSCO'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1HuV60oTwnapD5yUfRMhRxt9ukJUZSCO',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Landing Page Builders',
    'visibility' => 0,
  );

  $export['facetapi-1N1jjU1ibGMgfOWa4u8pOwTCpHRrop10'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1N1jjU1ibGMgfOWa4u8pOwTCpHRrop10',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1WE2DybvBMgmBO9SI5FDAJde1QdgK8FD'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1WE2DybvBMgmBO9SI5FDAJde1QdgK8FD',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'HTTP Public Key Pinning (HPKP)',
    'visibility' => 0,
  );

  $export['facetapi-1lcJzRh5ELFYDQdcB9sFkQvS3iIK91wk'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1lcJzRh5ELFYDQdcB9sFkQvS3iIK91wk',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1szZl7LRpkLoHqfVNJ11khU780tV7IZf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1szZl7LRpkLoHqfVNJ11khU780tV7IZf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1xTfDnIL2xAwgZR41u3Es1AZXzCajRvV'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1xTfDnIL2xAwgZR41u3Es1AZXzCajRvV',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1zkrU00wqmNjE1lxL80GzrcV0LwAFYK9'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1zkrU00wqmNjE1lxL80GzrcV0LwAFYK9',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-25cj194oE6mjM6UE1sdNjY1Ihvdrz7K2'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '25cj194oE6mjM6UE1sdNjY1Ihvdrz7K2',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'LMS Applications',
    'visibility' => 0,
  );

  $export['facetapi-29AdVE0IWV1T1taUCqw6ise71uisHRAf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '29AdVE0IWV1T1taUCqw6ise71uisHRAf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-2YjC0jkpLuDo83J5vKUePxYbVuECKyqJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '2YjC0jkpLuDo83J5vKUePxYbVuECKyqJ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'TLS V1 Support',
    'visibility' => 0,
  );

  $export['facetapi-2f5KEUMRkH7g8VAaZV09PP5Xard1AC1N'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '2f5KEUMRkH7g8VAaZV09PP5Xard1AC1N',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Ecommerce Applications',
    'visibility' => 0,
  );

  $export['facetapi-2lBM9irQyzh5tzBX2wq0RCxEO4EVihBf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '2lBM9irQyzh5tzBX2wq0RCxEO4EVihBf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Tag Managers',
    'visibility' => 0,
  );

  $export['facetapi-380NqOb0VbbHWCubpIM1QlJyVb5JRI6z'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '380NqOb0VbbHWCubpIM1QlJyVb5JRI6z',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-512YxmqomjdXZCq88eUGR6L1kVuYqUT1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '512YxmqomjdXZCq88eUGR6L1kVuYqUT1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-5nMaj2QHyFkNcch7WP05i2XrU05iBD0m'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '5nMaj2QHyFkNcch7WP05i2XrU05iBD0m',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-5wGfx9PaRUAlSkfsf3Rg47pXy1ljqOXi'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '5wGfx9PaRUAlSkfsf3Rg47pXy1ljqOXi',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Certificate Provider',
    'visibility' => 0,
  );

  $export['facetapi-6Zgnx9y3rxoyWwk7wgFl1W7QgIt31GY5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6Zgnx9y3rxoyWwk7wgFl1W7QgIt31GY5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'SSL V3 Support',
    'visibility' => 0,
  );

  $export['facetapi-6xYmKQ8vLL2wVseCqvdGE8oA1nZ8MCrV'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6xYmKQ8vLL2wVseCqvdGE8oA1nZ8MCrV',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Redirect',
    'visibility' => 0,
  );

  $export['facetapi-75GBNlcwLUoprelPjupbZ7Hs0nCrXXcW'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '75GBNlcwLUoprelPjupbZ7Hs0nCrXXcW',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'CMS Applications',
    'visibility' => 0,
  );

  $export['facetapi-7aDOrQM1QjK49aq3ikKS9qRVtnn4uZM5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7aDOrQM1QjK49aq3ikKS9qRVtnn4uZM5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-7lm9Bk6IKPvVHcAMaKV9ddvVy7XVPKbG'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7lm9Bk6IKPvVHcAMaKV9ddvVy7XVPKbG',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'XSS protection',
    'visibility' => 0,
  );

  $export['facetapi-9B9YMiF6M0BTv6WKgsZxT39kZmNEC37D'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '9B9YMiF6M0BTv6WKgsZxT39kZmNEC37D',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-9P1OXty7xdX0e1aWPkFXsxB0KZT05Wqh'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '9P1OXty7xdX0e1aWPkFXsxB0KZT05Wqh',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Marketing Automation',
    'visibility' => 0,
  );

  $export['facetapi-9heeA69glf6bfMdJ8w8gZGtWbf6Uk1GA'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '9heeA69glf6bfMdJ8w8gZGtWbf6Uk1GA',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-9wilj1gz0Kse2vc5wWtAl2S00QBF0FUT'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '9wilj1gz0Kse2vc5wWtAl2S00QBF0FUT',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Avjzj8RoxfiAWjKueVObMUvzr5BsH2AE'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Avjzj8RoxfiAWjKueVObMUvzr5BsH2AE',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'HTTPS Status',
    'visibility' => 0,
  );

  $export['facetapi-BJiLaU0uA4qiGUzIWSDLL3JGn0ZACSfm'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BJiLaU0uA4qiGUzIWSDLL3JGn0ZACSfm',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-BMEI98VxKaesg1LEMVIL4xo6K1AF4ljH'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BMEI98VxKaesg1LEMVIL4xo6K1AF4ljH',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-BTl1CDVWSWMTl6EskNHpX9l0vaRRNFUI'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BTl1CDVWSWMTl6EskNHpX9l0vaRRNFUI',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Enforce HTTPS',
    'visibility' => 0,
  );

  $export['facetapi-BUZYqpXQQ1RhOz0elA7NoIsC0a7GO9zv'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BUZYqpXQQ1RhOz0elA7NoIsC0a7GO9zv',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-BbjS6DaqUrTwWSS88HinJ5WdY8zb7S1Q'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BbjS6DaqUrTwWSS88HinJ5WdY8zb7S1Q',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Cloud Provider',
    'visibility' => 0,
  );

  $export['facetapi-BmDqb1FEjNIyOT8kT4uwdBo6KWdLvyeP'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'BmDqb1FEjNIyOT8kT4uwdBo6KWdLvyeP',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Certificate - OCSP Stapling',
    'visibility' => 0,
  );

  $export['facetapi-CLDYLyvTfoZKlHmTtdgIIQ1TlHczuoHL'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'CLDYLyvTfoZKlHmTtdgIIQ1TlHczuoHL',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Agency',
    'visibility' => 0,
  );

  $export['facetapi-D5c1cWgyn87ADso0QmXX28vnTLCD8o92'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'D5c1cWgyn87ADso0QmXX28vnTLCD8o92',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-D911TBQtmzdrE1djmeYc16CLNnP3mgbb'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'D911TBQtmzdrE1djmeYc16CLNnP3mgbb',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'HSTS Status',
    'visibility' => 0,
  );

  $export['facetapi-DLETk9UypJr2wwnUlOxC311oVZGpE9Re'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'DLETk9UypJr2wwnUlOxC311oVZGpE9Re',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'OpenSSL Heartbleed',
    'visibility' => 0,
  );

  $export['facetapi-DWiN7DELXnsTvBFInGOfcw7UO3avAL4N'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'DWiN7DELXnsTvBFInGOfcw7UO3avAL4N',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-DY0JcJHsQLWrMqdvFtH8TAN1To91PSnG'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'DY0JcJHsQLWrMqdvFtH8TAN1To91PSnG',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-E72gC9peZWfo7VULa4mtjt1UhiuGm7S5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'E72gC9peZWfo7VULa4mtjt1UhiuGm7S5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ERANgcaU9Ge2jq9bXroQtqAyFktX7z4O'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ERANgcaU9Ge2jq9bXroQtqAyFktX7z4O',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Uses Cookies',
    'visibility' => 0,
  );

  $export['facetapi-F12rZrdILhsKm2xwxtYoztEQiGIC7ovk'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'F12rZrdILhsKm2xwxtYoztEQiGIC7ovk',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Widget Applications',
    'visibility' => 0,
  );

  $export['facetapi-F1YLnHEkz5dibDJ5FQAtlqFLJyt7afPX'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'F1YLnHEkz5dibDJ5FQAtlqFLJyt7afPX',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-FZ3VFhHzpWl5ndzUxH0Yh7AxxxsVP7CR'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'FZ3VFhHzpWl5ndzUxH0Yh7AxxxsVP7CR',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'RC4 Status',
    'visibility' => 0,
  );

  $export['facetapi-GW0FDePwlD16eoCETv5RGLOCYp7h9NIr'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'GW0FDePwlD16eoCETv5RGLOCYp7h9NIr',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Databases',
    'visibility' => 0,
  );

  $export['facetapi-GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Filter By Content Type',
    'visibility' => 0,
  );

  $export['facetapi-GiPncE24sZPo5FQ6qyQgfKkg6JFY8mr6'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'GiPncE24sZPo5FQ6qyQgfKkg6JFY8mr6',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Build CI Systems',
    'visibility' => 0,
  );

  $export['facetapi-GogA75YwFlryK5qE6y2nR77cS0EuXc0z'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'GogA75YwFlryK5qE6y2nR77cS0EuXc0z',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-HElHllnoCDr80rCZEooDrqtgmVl1WskU'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'HElHllnoCDr80rCZEooDrqtgmVl1WskU',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Analytics Applications',
    'visibility' => 0,
  );

  $export['facetapi-HNGeH1jcVAi4r08o4G4mey2dh0CeDgtq'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'HNGeH1jcVAi4r08o4G4mey2dh0CeDgtq',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-JdhXlkP4rAS8LCZsmnODj7gG04uee53H'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'JdhXlkP4rAS8LCZsmnODj7gG04uee53H',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Jm0nudvscZjwxIsbLNz9aCOpbOyJsBzQ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Jm0nudvscZjwxIsbLNz9aCOpbOyJsBzQ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-KJhRd1mKJ3hzygJSdEnFJ6kF1C9FEnm2'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'KJhRd1mKJ3hzygJSdEnFJ6kF1C9FEnm2',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'CDN Provider',
    'visibility' => 0,
  );

  $export['facetapi-LodmcvgmCjm7EJJ6PyTsVaIffjgYBL7g'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'LodmcvgmCjm7EJJ6PyTsVaIffjgYBL7g',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Captcha Applications',
    'visibility' => 0,
  );

  $export['facetapi-McTZFEAYIvpqRxBAyyqzSx224Ukyy8Uc'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'McTZFEAYIvpqRxBAyyqzSx224Ukyy8Uc',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-PyQ7pt3sBFbFaLGfUa2LxWwQEEvAxvKZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'PyQ7pt3sBFbFaLGfUa2LxWwQEEvAxvKZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-QV0C3iB8f4Sp8nZiEl7xfMdy6yODwvaq'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'QV0C3iB8f4Sp8nZiEl7xfMdy6yODwvaq',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Uses Robots.txt',
    'visibility' => 0,
  );

  $export['facetapi-QpaPRpIcOFIeAPf0rcXNsxro7HLl0a8A'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'QpaPRpIcOFIeAPf0rcXNsxro7HLl0a8A',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-RT8QSIFGgAE8E3WpCrFq1xUouhSyw5l0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'RT8QSIFGgAE8E3WpCrFq1xUouhSyw5l0',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'TLS V1.2 Support',
    'visibility' => 0,
  );

  $export['facetapi-TeQmklSiwcz465RIzGdv45roPNuE0ean'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'TeQmklSiwcz465RIzGdv45roPNuE0ean',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-TvhfpJzMXiIfTQiyBbsn17wY3UrhJWi8'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'TvhfpJzMXiIfTQiyBbsn17wY3UrhJWi8',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Have proper 404',
    'visibility' => 0,
  );

  $export['facetapi-UVAt7FJR02ZsJ01fV88QugLUVdzB2iwA'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'UVAt7FJR02ZsJ01fV88QugLUVdzB2iwA',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Video Players',
    'visibility' => 0,
  );

  $export['facetapi-UmFvLEl20H8GQHgQiwOt6N4wjBBWtMAm'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'UmFvLEl20H8GQHgQiwOt6N4wjBBWtMAm',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Certificate Issuer',
    'visibility' => 0,
  );

  $export['facetapi-UtK0707P0MZIRNgUyu7jlqVwryCbPjI7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'UtK0707P0MZIRNgUyu7jlqVwryCbPjI7',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'OpenSSL CCS Injection',
    'visibility' => 0,
  );

  $export['facetapi-V5VY4NoBmsg3vfANfnUCtpUuyRX3Y9zp'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'V5VY4NoBmsg3vfANfnUCtpUuyRX3Y9zp',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Mobile Frameworks',
    'visibility' => 0,
  );

  $export['facetapi-VkPYVKNQPWO00Oy5JBWW3fxX0ss3pV7X'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'VkPYVKNQPWO00Oy5JBWW3fxX0ss3pV7X',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-W0rny1I0put4O9b4EtKi8dmcXuGc2zyY'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'W0rny1I0put4O9b4EtKi8dmcXuGc2zyY',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-X8a1kbtYWy1xJhbAF6qN0blUSax7XfOm'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'X8a1kbtYWy1xJhbAF6qN0blUSax7XfOm',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Y0yU0xSa0kBQrD61IWczp4tSawx7yGG3'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Y0yU0xSa0kBQrD61IWczp4tSawx7yGG3',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Y8J9bU0Vvel2CZZl25wIEEeZ2yeaXvoC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Y8J9bU0Vvel2CZZl25wIEEeZ2yeaXvoC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-YRU2BCPw61a7RMtIF3moMj0cA161YCqb'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'YRU2BCPw61a7RMtIF3moMj0cA161YCqb',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Z21pXGxS8svBcnJoSr0Ihc1ci8KSEQcp'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Z21pXGxS8svBcnJoSr0Ihc1ci8KSEQcp',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ZLA8QXnOOLyjJ5lvVhvF1hXp07X6tFvk'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ZLA8QXnOOLyjJ5lvVhvF1hXp07X6tFvk',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ZZ5ecHjXlDx19RszAOsVsP7cTsbu8GEW'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ZZ5ecHjXlDx19RszAOsVsP7cTsbu8GEW',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Zk2E7ARHMLPxIPZuddgTNUBh7l01jR7u'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Zk2E7ARHMLPxIPZuddgTNUBh7l01jR7u',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ZlF1quwma7FzBwJXSOO2VEExcGCnWAvC'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ZlF1quwma7FzBwJXSOO2VEExcGCnWAvC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Javascript Frameworks',
    'visibility' => 0,
  );

  $export['facetapi-Zo8e0Lpr90BjR0BHW1F7pGOUGKxf0hCL'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Zo8e0Lpr90BjR0BHW1F7pGOUGKxf0hCL',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-a1fFS9jv2Cq3UDSpjCqxl916PHAXS6O0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'a1fFS9jv2Cq3UDSpjCqxl916PHAXS6O0',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-aBzpmggam0xTiO0vPX8Rlu0dtWHWQKKy'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'aBzpmggam0xTiO0vPX8Rlu0dtWHWQKKy',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Cache Tools',
    'visibility' => 0,
  );

  $export['facetapi-aKo19sU0875wh9y5Ohlr55Kw18FwLgwt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'aKo19sU0875wh9y5Ohlr55Kw18FwLgwt',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-aOQGmd0jxWs7ldW31WbAmFnDDw2NNSnl'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'aOQGmd0jxWs7ldW31WbAmFnDDw2NNSnl',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Web Server Extensions',
    'visibility' => 0,
  );

  $export['facetapi-b1xT9T3YpLPSOzHiwBS5N5DY0QBkBeMP'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'b1xT9T3YpLPSOzHiwBS5N5DY0QBkBeMP',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-bk0405OO60p6nQ17XVxOrSdKuDJaq0y5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'bk0405OO60p6nQ17XVxOrSdKuDJaq0y5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Website Tags',
    'visibility' => 0,
  );

  $export['facetapi-cHYMgZkhnabLSJ08pkDyIvYRpSoHSipJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cHYMgZkhnabLSJ08pkDyIvYRpSoHSipJ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-cR5A29Lb9DogdsnumZESdchW7gp8h5Jl'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cR5A29Lb9DogdsnumZESdchW7gp8h5Jl',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Rich Text Editors',
    'visibility' => 0,
  );

  $export['facetapi-cqj8kIUqrK1fhr5mvDw14AjC4nZ2uRpy'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cqj8kIUqrK1fhr5mvDw14AjC4nZ2uRpy',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-crUBTkgrzB2gabWRwpea0MIi8KvsqdlR'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'crUBTkgrzB2gabWRwpea0MIi8KvsqdlR',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Advertising Networks',
    'visibility' => 0,
  );

  $export['facetapi-cxDmV0KFBCNFhOf5G9IBJcyur6oq9wBi'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cxDmV0KFBCNFhOf5G9IBJcyur6oq9wBi',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Uses Secure Cookies',
    'visibility' => 0,
  );

  $export['facetapi-dGqetQNLiPEHu2WVpMs4FbQkuqtS4GNx'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'dGqetQNLiPEHu2WVpMs4FbQkuqtS4GNx',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-dH2y0uVkHfoI21Vy2lYtXdHUE2vq1urJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'dH2y0uVkHfoI21Vy2lYtXdHUE2vq1urJ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-dWzRKSXRgm1BfPgUGPlpb9uOFXu51oLL'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'dWzRKSXRgm1BfPgUGPlpb9uOFXu51oLL',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-dg0JDYE00PdN8vqO2b2JjpfMHZE1Cf3F'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'dg0JDYE00PdN8vqO2b2JjpfMHZE1Cf3F',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-e99EBWZhnE8tIcEe4VUcBD4m0vyvo8MT'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'e99EBWZhnE8tIcEe4VUcBD4m0vyvo8MT',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '3DES Status',
    'visibility' => 0,
  );

  $export['facetapi-eBn2gMxPLGFd6bd6X368KsK0wQLcBD5G'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'eBn2gMxPLGFd6bd6X368KsK0wQLcBD5G',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Issue Trackers',
    'visibility' => 0,
  );

  $export['facetapi-f767L49XIkOM5zGxvuMzEKGLVR7BPpRg'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'f767L49XIkOM5zGxvuMzEKGLVR7BPpRg',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-gQR044z7FOsi2xWcggDHIUOvYpWS4p0P'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'gQR044z7FOsi2xWcggDHIUOvYpWS4p0P',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Photo Galleries',
    'visibility' => 0,
  );

  $export['facetapi-hnVFv19AprmQCJyiECmKsArbelo6eokY'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'hnVFv19AprmQCJyiECmKsArbelo6eokY',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-iRGuc7rV3Mb7aksWSlGFezZdG3NqgtiF'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'iRGuc7rV3Mb7aksWSlGFezZdG3NqgtiF',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'CRM Applications',
    'visibility' => 0,
  );

  $export['facetapi-iTpca1eeOcSBAw307FoDam6od2ru3gOR'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'iTpca1eeOcSBAw307FoDam6od2ru3gOR',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Deflate Compression',
    'visibility' => 0,
  );

  $export['facetapi-im04lYh9mepwYB7GLPY0DE10yNOKw4p0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'im04lYh9mepwYB7GLPY0DE10yNOKw4p0',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Miscellaneous Application',
    'visibility' => 0,
  );

  $export['facetapi-j3qjONDoIcvrCD7l0IPWNizy5rKBOOU7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'j3qjONDoIcvrCD7l0IPWNizy5rKBOOU7',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-jIfHrhSTOdJRs7d2VxTwOty1NgsO4w21'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jIfHrhSTOdJRs7d2VxTwOty1NgsO4w21',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-kWuYTykBrOHHbkZVhzzX8571AjjYDq0s'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'kWuYTykBrOHHbkZVhzzX8571AjjYDq0s',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Click jacking protection',
    'visibility' => 0,
  );

  $export['facetapi-kYxYkRqcDiNYi0BHUzHFF9CfcroNZZVZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'kYxYkRqcDiNYi0BHUzHFF9CfcroNZZVZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-kvPlNPRcztUlILywblxC9Kj14ZYJ7Dnw'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'kvPlNPRcztUlILywblxC9Kj14ZYJ7Dnw',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'TLS V1.1',
    'visibility' => 0,
  );

  $export['facetapi-lfFvZQW1qtjlk6e19NwBOl5jlMxdjPXd'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'lfFvZQW1qtjlk6e19NwBOl5jlMxdjPXd',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-mIYsI7u71fTfm0Q4Pzkx1lPJW5nppD2g'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'mIYsI7u71fTfm0Q4Pzkx1lPJW5nppD2g',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-mzhFnMHHdi6wkverMbzpP2bDeh31oD3D'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'mzhFnMHHdi6wkverMbzpP2bDeh31oD3D',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-nD01203UOLmCEPDrBTinpwzcqBw2j15x'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nD01203UOLmCEPDrBTinpwzcqBw2j15x',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Payment Processors',
    'visibility' => 0,
  );

  $export['facetapi-nPJlJIkvEz5FzIq40hrJxUXWiG0CjfIu'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nPJlJIkvEz5FzIq40hrJxUXWiG0CjfIu',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-nVGxnv8kQdaFBggr5Ogd3fgz3ftjtQCM'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nVGxnv8kQdaFBggr5Ogd3fgz3ftjtQCM',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Operating Systems',
    'visibility' => 0,
  );

  $export['facetapi-oRlwDqDrVXc2wTVBoEsQtiJ1Gh4ITiqt'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'oRlwDqDrVXc2wTVBoEsQtiJ1Gh4ITiqt',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => ' JavaScript Graphics applications',
    'visibility' => 0,
  );

  $export['facetapi-oqvMYfIAMLclwyulLYuiFh61IZ050kki'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'oqvMYfIAMLclwyulLYuiFh61IZ050kki',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Free of RC4/3DES and SSLv2/SSLv3',
    'visibility' => 0,
  );

  $export['facetapi-osRUpMUI017Nm06J22kxWEywmGCC0e5M'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'osRUpMUI017Nm06J22kxWEywmGCC0e5M',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Downgrade Attacks',
    'visibility' => 0,
  );

  $export['facetapi-pMhkC11V0SxJzglcNo7wjkR6AFToA31D'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pMhkC11V0SxJzglcNo7wjkR6AFToA31D',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-pQ3udOiKNVtL1YcpTPiAQs91jIHAx901'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pQ3udOiKNVtL1YcpTPiAQs91jIHAx901',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-pcN5VPfSYqla7hbDPX3C1KL7nU3fHkMc'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pcN5VPfSYqla7hbDPX3C1KL7nU3fHkMc',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-puGASfwGBgxqw2OLjupootf0hh1j0Vov'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'puGASfwGBgxqw2OLjupootf0hh1j0Vov',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'SSL V2 Support',
    'visibility' => 0,
  );

  $export['facetapi-r0dqywabRcnO6tf9wk6alPUtKRRA1nH8'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'r0dqywabRcnO6tf9wk6alPUtKRRA1nH8',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-rFOkYnHpSFLGeJYHUQdGoP2mYL1vbx9g'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'rFOkYnHpSFLGeJYHUQdGoP2mYL1vbx9g',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Programming Languages',
    'visibility' => 0,
  );

  $export['facetapi-rnrOMRLT5sZRqXu2TsuHQZBSDMT61oab'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'rnrOMRLT5sZRqXu2TsuHQZBSDMT61oab',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-sHU3WUBSrGelRXfLF120vfTBD911YXju'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'sHU3WUBSrGelRXfLF120vfTBD911YXju',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-scLih0KmYM1v1nD5OXm10Q9G1xnfbxqg'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'scLih0KmYM1v1nD5OXm10Q9G1xnfbxqg',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-shjwkfuQuEu3djSysY1QF9sF820bqHUF'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'shjwkfuQuEu3djSysY1QF9sF820bqHUF',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-tU0n3Dk2BIg1jdXb39uJ6fsjj0syEyqd'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'tU0n3Dk2BIg1jdXb39uJ6fsjj0syEyqd',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-tVKFqsX0tXFjqNAOn0dm9TFOe3zmCnEB'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'tVKFqsX0tXFjqNAOn0dm9TFOe3zmCnEB',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'DAP Status',
    'visibility' => 0,
  );

  $export['facetapi-u7o62PnqdpTiCQJ8Jg6DEnKt2pHZZALw'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'u7o62PnqdpTiCQJ8Jg6DEnKt2pHZZALw',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ukU3gG46bAP0T0Lp3IZbZg5glHHJA0h7'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ukU3gG46bAP0T0Lp3IZbZg5glHHJA0h7',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'SSL Certificate Status',
    'visibility' => 0,
  );

  $export['facetapi-v8CVSJdPtq988H67x3fPAeYe5L1n6iyf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'v8CVSJdPtq988H67x3fPAeYe5L1n6iyf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Web Frameworks',
    'visibility' => 0,
  );

  $export['facetapi-vxFxdg4pvr60fqe0P1GeFgGoNpHF0yKb'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'vxFxdg4pvr60fqe0P1GeFgGoNpHF0yKb',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-wAO61TUv11OJRNxHYD1dSVC0kv16ud60'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'wAO61TUv11OJRNxHYD1dSVC0kv16ud60',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-wQptPRO3p0NeEVJqDLJdwBOuIi1eeSPy'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'wQptPRO3p0NeEVJqDLJdwBOuIi1eeSPy',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Compliant with M-15-13 and BOD 18-01',
    'visibility' => 0,
  );

  $export['facetapi-wt432Z7yoz0p4fEJ5uUjMonW07Ldt3TV'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'wt432Z7yoz0p4fEJ5uUjMonW07Ldt3TV',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-xPCqHIqG05Th8En9d0u0DTfWUVIwpCSr'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'xPCqHIqG05Th8En9d0u0DTfWUVIwpCSr',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Editor Applications',
    'visibility' => 0,
  );

  $export['facetapi-xmOisbopt7sEA41aousfrsujBgQ0lLSZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'xmOisbopt7sEA41aousfrsujBgQ0lLSZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Hosting Panels',
    'visibility' => 0,
  );

  $export['facetapi-y054hLlBC6kqutDj1wUZznZalZ9kEUxa'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'y054hLlBC6kqutDj1wUZznZalZ9kEUxa',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'Maps Applications',
    'visibility' => 0,
  );

  $export['facetapi-y5Kxc70Lb6FwHeh8MnddkuRcwZo10Lbx'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'y5Kxc70Lb6FwHeh8MnddkuRcwZo10Lbx',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => 'CDN applications',
    'visibility' => 0,
  );

  $export['facetapi-yWQkVPcUHOZQgROk0gHFbYYhCdAgd60h'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'yWQkVPcUHOZQgROk0gHFbYYhCdAgd60h',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-za1OPkNT7J9UtcjHG9B0IhVBjmGxsali'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'za1OPkNT7J9UtcjHG9B0IhVBjmGxsali',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-zbAsYHMvXMtWZgnz2hSSJecFz0Kgrd3M'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zbAsYHMvXMtWZgnz2hSSJecFz0Kgrd3M',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-zoU2Tp1AWna63Ld0PPo0LgK6YvpCuuL1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zoU2Tp1AWna63Ld0PPo0LgK6YvpCuuL1',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['panels_mini-uswds_search_facets'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'uswds_search_facets',
    'module' => 'panels_mini',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['trend_analysis-trends_uswds'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'trends_uswds',
    'module' => 'trend_analysis',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['trend_analysis-trends_uswds_sparkline'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'trends_uswds_sparkline',
    'module' => 'trend_analysis',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-all_agency_data-block_19'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'all_agency_data-block_19',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-https-block_1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'https-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block_1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block_1',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block_13'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block_13',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block_2'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block_2',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block_3'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block_3',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block_4'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block_4',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block_5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block_5',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
