<?php
/**
 * @file
 * accessibility_new.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function accessibility_new_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-508_scan_information-field_accessibility_raw_scan'.
  $field_instances['node-508_scan_information-field_accessibility_raw_scan'] = array(
    'bundle' => '508_scan_information',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_accessibility_raw_scan',
    'label' => 'Accessibility Raw scan',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 32,
    ),
  );

  // Exported field_instance:
  // 'node-508_scan_information-field_accessible_group_colorcont'.
  $field_instances['node-508_scan_information-field_accessible_group_colorcont'] = array(
    'bundle' => '508_scan_information',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_accessible_group_colorcont',
    'label' => 'Accessibility Group Color Contrast',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 33,
    ),
  );

  // Exported field_instance:
  // 'node-508_scan_information-field_accessible_group_htmlattri'.
  $field_instances['node-508_scan_information-field_accessible_group_htmlattri'] = array(
    'bundle' => '508_scan_information',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 10,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_accessible_group_htmlattri',
    'label' => 'Accessibility Group HTML Attribute',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 34,
    ),
  );

  // Exported field_instance:
  // 'node-508_scan_information-field_accessible_group_missingim'.
  $field_instances['node-508_scan_information-field_accessible_group_missingim'] = array(
    'bundle' => '508_scan_information',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 11,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_accessible_group_missingim',
    'label' => 'Accessibility Group Missing Image',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 35,
    ),
  );

  // Exported field_instance: 'node-accessibility_agency_scan_inform-body'.
  $field_instances['node-accessibility_agency_scan_inform-body'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Agency Scan Raw',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Agency Scan Raw',
    'required' => 0,
    'settings' => array(
      'display_summary' => 1,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_agac_agency_pages_cnt'.
  $field_instances['node-accessibility_agency_scan_inform-field_agac_agency_pages_cnt'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Agency Pages Count',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_agac_agency_pages_cnt',
    'label' => 'Agency Pages Count',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_agac_average_errors_page'.
  $field_instances['node-accessibility_agency_scan_inform-field_agac_average_errors_page'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Average Errors per Page',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 2,
          'thousand_separator' => '',
        ),
        'type' => 'number_decimal',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_agac_average_errors_page',
    'label' => 'Average Errors per Page',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 7,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_agac_color_contrast_aver'.
  $field_instances['node-accessibility_agency_scan_inform-field_agac_color_contrast_aver'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Agency Color Contrast Average',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 2,
          'thousand_separator' => '',
        ),
        'type' => 'number_decimal',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_agac_color_contrast_aver',
    'label' => 'Agency Color Contrast Average',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 9,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_agac_form_init_find_avrg'.
  $field_instances['node-accessibility_agency_scan_inform-field_agac_form_init_find_avrg'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Agency Form - Initial Findings Average',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 2,
          'thousand_separator' => '',
        ),
        'type' => 'number_decimal',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_agac_form_init_find_avrg',
    'label' => 'Agency Form - Initial Findings Average',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 12,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_agac_html_attribute_avrg'.
  $field_instances['node-accessibility_agency_scan_inform-field_agac_html_attribute_avrg'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Agency HTML Attribute - Initial Findings Average',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 2,
          'thousand_separator' => '',
        ),
        'type' => 'number_decimal',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_agac_html_attribute_avrg',
    'label' => 'Agency HTML Attribute - Initial Findings Average',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 11,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_agac_missing_image_avrg'.
  $field_instances['node-accessibility_agency_scan_inform-field_agac_missing_image_avrg'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Agency Missing Image Descriptions Average',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 2,
          'thousand_separator' => '',
        ),
        'type' => 'number_decimal',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_agac_missing_image_avrg',
    'label' => 'Agency Missing Image Descriptions Average',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 10,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_web_agency_id'.
  $field_instances['node-accessibility_agency_scan_inform-field_web_agency_id'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Agency Id',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'node_reference',
        'settings' => array(),
        'type' => 'node_reference_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_web_agency_id',
    'label' => 'Agency Id',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'node-accessibility_agency_scan_inform-field_web_scan_id'.
  $field_instances['node-accessibility_agency_scan_inform-field_web_scan_id'] = array(
    'bundle' => 'accessibility_agency_scan_inform',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Scan ID',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'node_reference',
        'settings' => array(),
        'type' => 'node_reference_default',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_web_scan_id',
    'label' => 'Scan ID',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Accessibility Group Color Contrast');
  t('Accessibility Group HTML Attribute');
  t('Accessibility Group Missing Image');
  t('Accessibility Raw scan');
  t('Agency Color Contrast Average');
  t('Agency Form - Initial Findings Average');
  t('Agency HTML Attribute - Initial Findings Average');
  t('Agency Id');
  t('Agency Missing Image Descriptions Average');
  t('Agency Pages Count');
  t('Agency Scan Raw');
  t('Average Errors per Page');
  t('Scan ID');

  return $field_instances;
}
