<?php
/**
 * Created by PhpStorm.
 * User: kapilbulchandani
 * Date: 5/18/17
 * Time: 7:53 PM
 */


function activity_chart_chart_alter(&$chart, $chart_id) {
    if ($chart_id === 'website_information__attachment_3') {
        // Individual properties may be modified.
       drupal_add_js('https://code.highcharts.com/highcharts-more.js');
        drupal_add_js('https://code.highcharts.com/modules/solid-gauge.js');
       // drupal_add_js(drupal_get_path('module', 'activity_chart') . '/activity_chart.js');
   // dsm($chart);
     $chart['#title'] = 'test';
     $chart['#chart_type']='solidgauge';


    }

}
