<?php

/**
 * @file
 * uswds_settings.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function uswds_settings_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-1N1jjU1ibGMgfOWa4u8pOwTCpHRrop10'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1N1jjU1ibGMgfOWa4u8pOwTCpHRrop10',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1szZl7LRpkLoHqfVNJ11khU780tV7IZf'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1szZl7LRpkLoHqfVNJ11khU780tV7IZf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-1zkrU00wqmNjE1lxL80GzrcV0LwAFYK9'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '1zkrU00wqmNjE1lxL80GzrcV0LwAFYK9',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-380NqOb0VbbHWCubpIM1QlJyVb5JRI6z'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '380NqOb0VbbHWCubpIM1QlJyVb5JRI6z',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-7aDOrQM1QjK49aq3ikKS9qRVtnn4uZM5'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7aDOrQM1QjK49aq3ikKS9qRVtnn4uZM5',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Jm0nudvscZjwxIsbLNz9aCOpbOyJsBzQ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Jm0nudvscZjwxIsbLNz9aCOpbOyJsBzQ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-TeQmklSiwcz465RIzGdv45roPNuE0ean'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'TeQmklSiwcz465RIzGdv45roPNuE0ean',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-YRU2BCPw61a7RMtIF3moMj0cA161YCqb'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'YRU2BCPw61a7RMtIF3moMj0cA161YCqb',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-ZLA8QXnOOLyjJ5lvVhvF1hXp07X6tFvk'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'ZLA8QXnOOLyjJ5lvVhvF1hXp07X6tFvk',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-cHYMgZkhnabLSJ08pkDyIvYRpSoHSipJ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'cHYMgZkhnabLSJ08pkDyIvYRpSoHSipJ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-jIfHrhSTOdJRs7d2VxTwOty1NgsO4w21'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'jIfHrhSTOdJRs7d2VxTwOty1NgsO4w21',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-nPJlJIkvEz5FzIq40hrJxUXWiG0CjfIu'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'nPJlJIkvEz5FzIq40hrJxUXWiG0CjfIu',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-pMhkC11V0SxJzglcNo7wjkR6AFToA31D'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'pMhkC11V0SxJzglcNo7wjkR6AFToA31D',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-wt432Z7yoz0p4fEJ5uUjMonW07Ldt3TV'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'wt432Z7yoz0p4fEJ5uUjMonW07Ldt3TV',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-zbAsYHMvXMtWZgnz2hSSJecFz0Kgrd3M'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'zbAsYHMvXMtWZgnz2hSSJecFz0Kgrd3M',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['panels_mini-uswds_search_facets'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'uswds_search_facets',
    'module' => 'panels_mini',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['trend_analysis-trends_uswds'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'trends_uswds',
    'module' => 'trend_analysis',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['trend_analysis-trends_uswds_sparkline'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'trends_uswds_sparkline',
    'module' => 'trend_analysis',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-all_agency_data-block_19'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'all_agency_data-block_19',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-website_information-block_13'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'website_information-block_13',
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'dotgov' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'dotgov',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
