<?php
/*
* Digital Dashboard Website Reports
*/

function dd_website_reports_views_pre_render(&$view){
  if ($view->name == 'all_website_reports_new') {
    drupal_add_library('system', 'ui.accordion');
    //drupal_add_js('jQuery(document).ready(function () { jQuery(".view-all-website-reports-new.view-display-id-page_1 .view-content").accordion( { collapsible: true } ); });', 'inline');
    
    drupal_add_js(drupal_get_path('module', 'dd_website_reports') . '/dd_website_reports.js');
    
    $path = libraries_get_path('tablesorter');
    drupal_add_js($path . '/js/jquery.tablesorter.min.js');
    //drupal_add_css($path . '/css/theme.blue.css');
  }
}
