<?php
/*
* Dotgov Dashboard common functions module
*/

function dotgov_common_siteAsocScanids($websiteid){
    $node = node_load($websiteid);

    $query = db_query("select bundle,entity_id from field_data_field_website_id where field_website_id_nid=:nid", array(':nid' => $websiteid));
    foreach ($query as $result) {
        $websites[$result->bundle] = $result->entity_id;
    }
    return $websites;
}

/**
 * Implements hook_action_info().
 */
function dotgov_common_getNodeTaxonomy($nid)
{
    $terms = array();
    $results = db_query('SELECT b.tid tid ,b.name name  FROM {taxonomy_index} a, {taxonomy_term_data b}  WHERE a.tid=b.tid and a.nid=:nid', array(':nid' => $nid));
    foreach ($results as $result) {
        $terms[$result->tid] = $result->name;
    }
  return $terms;

}

/*
 * Find Last scan date
 */
function dotgov_common_lastScanDate(){
  $query = db_query("select nid,created from node where type='scans' order by nid desc limit 1");
  foreach ($query as $result) {
    $lastscantime = $result->created;
  }
  print date("m/d/Y",$lastscantime);
}

/*
* Hook Facet Alter
*/

function dotgov_common_facet_items_alter(&$build, &$settings) {
$enabled_fields =  array("sm_field_hsts_status","ism_field_https_status","sm_field_redirect","bm_field_ssl_v2_support","bm_field_ssl_v3_support","bm_field_tls_v1_support","bm_field_tls_v1_1_support","bm_field_tls_v1_2_support","bm_field_certificate_ocsp_stapli","bm_field_http_public_hpkp","bm_field_deflate_compression","bm_field_session_secure_renegoti","bm_field_have_proper_404","sm_field_enforce_https","bm_field_dap_status","bm_field_xss_protection");
$vulnerable_fields = array("bm_field_openssl_ccs_injection","bm_field_openssl_heartbleed","bm_field_downgrade_attacks");
                        if (in_array($settings->facet,$enabled_fields)) {
                          foreach($build as $key => $item) {
				if($key == 'true')	
                            		$build[$key]["#markup"] = "Enabled";
				elseif($key == 'false')	
                            		$build[$key]["#markup"] = "Disabled";
                          }
                        }
			if(in_array($settings->facet,$vulnerable_fields)) {
                          foreach($build as $key => $item) {
                                if($key == 'true')
                                        $build[$key]["#markup"] = "Vulnerable";
                                elseif($key == 'false')
                                        $build[$key]["#markup"] = "Not Vulnerable";
                          }
                        }


}
