language: python
python:
  - "2.7"
  - "3.6"
# Command to install dependencies
install:
  - pip install -U pip setuptools
  - pip install -r requirements.txt
# Command to run tests
script: "python run_tests.py"
